[package]
name = "pathfinder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-console = "0.2.1"
gloo-timers = "0.2.4"
gloo-utils = "0.1.3"
yew = "0.19"
